### ISSUE TITLE
Negative temperatures

### ISSUE THREAD

**Issue by aertw** [codyc1515/homebridge-ismartgate#7]
It looks like the plugin is ignoring negative temperatures. While it is minus 6, the plugin shows 0 degrees.

Debug log shows the correct info: Successfully obtained temperature. [ '-6000', 'full' ]

**Comment by Quickstep3** [comment]
Also got this issue with the logs showing:
showing
[11/02/2021, 06:52:04] Received warning for the plugin 'homebridge-ismartgate' from the characteristic 'Current Temperature': characteristic was supplied illegal value: number -0.4 exceeded minimum of 0.

this is running the latest homebridge beta 1.3.0 beta54

**Comment by Quickstep3** [comment]
Seems the default minValue for a TemperatureSensor characteristic of an accessory is 0 and this needs to be overridden. https://github.com/homebridge/HAP-NodeJS/issues/147

**Comment by Quickstep3** [comment]
This has apparently now been fixed in the main Homebridge component (see https://github.com/homebridge/homebridge/issues/2799) but we’ll need to wait for another cold snap to confirm!

**Comment by codyc1515** [comment]
Any luck?

**Comment by Quickstep3** [comment]
Not got cold enough overnight here yet to notice if there is still an issue. Forecast to be -4 later this week so we may see it dip below zero in the garage

**Comment by aertw** [comment]
Negative temperatures are still not working, but I’m still using version 1.3.0. More recent versions can’t cope with multiple iSmartgate instances.

**Comment by codyc1515** [comment]
You may wish to check out Home Assistant which has a native iSmartGate integration.
